### ISSUE TITLE
REQ: Rebase against z-push 2.2.latest

### ISSUE THREAD

**Issue by raoulbhatia** [fmbiete/Z-Push-contrib#257]
Hi,

any plans to rebase z-push-contrib against the latest z-push 2.2.x release?

They recently switched to git so keeping those two projects in sync should now be much easier.

Thanks,
Raoul

**Comment by fmbiete** [comment]
Yes and no. I put some info already in #240 

I won't be rebasing against 2.2.7, because is a nightmare. But this repo already have almost all the changes from that version, if you feel that something is missing let me know and I will look into backporting that one.

I am rebasing the code against develop branch, because it will be easier since upstream is accepting bigger changes in there (for example 2.2 series won't have auto-includes but 3.0 yes...)

**Comment by raoulbhatia** [comment]
So will you re-base against anything that is like 2.3?
see http://z-push.org/z-push-2-3-0-alpha2-released/

Those look like worthwhile changes :)

Thanks,
Raoul

**Comment by compuguy** [comment]
Looks like they have caught up in the past 2 years (cardav and caldav modules are available): http://z-push.org/z-push-2-3-8-final-release/

**Comment by raoulbhatia** [comment]
Few days back i've installed z-push 2.3.9 via http://z-push.org/z-push-2-3-9-final-release/ .
First tests look good :-) awesome stuff!
